language: node_js
node_js:
  - '8'
  - 'node'
jobs:
  include:
    - stage: Lint and test
      name: Test
      script: npm test
    - script: npm run lint
      name: Lint
    - stage: deploy
      node_js: 'node'
      if: branch = master
      name: Release to npm
      script: npm run semantic-release
    - script: npm run coveralls
      name: Coveralls
